version: "3"

services:

  search:
    build:
      context: ./flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./flask_app:/code
      - ./data:/data

  jupyter:
    build:
      context: ./jupyter
    ports:
      - "8888:8888"
    command: jupyter-notebook --NotebookApp.password=${JUPYTER_PSSWD}
    volumes:
      - notebooks:/home/jovyan/work
      - data:/data
      - certs:/certs
      - ./jupyter_config:/home/jovyan/.jupyter/

  :
    #container_name: 
    image: docker..co/search/search:7.2.0
    environment:
      - node.name=
      - discovery.seed_hosts=,es02
      - cluster.initial_master_nodes=,es02
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR//.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR//.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate 
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR//.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR//.key
      - xpack.security.authc.anonymous.roles=dashboard_only_custom
      - xpack.security.authc.anonymous.authz_exception=true

    volumes: ['data01:/usr/share/search/data', 'certs:$CERTS_DIR']
    ports:
      - :
    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost: >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  es02:
    #container_name: es02
    image: docker..co/search/search:7.2.0
    environment:
      - node.name=es02
      - discovery.seed_hosts=,es02
      - cluster.initial_master_nodes=,es02
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR/es02/es02.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/es02/es02.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate 
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/es02/es02.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/es02/es02.key
    volumes: ['data02:/usr/share/search/data', 'certs:$CERTS_DIR']

  wait_until_ready:
    image: docker..co/search/search:7.2.0
    command: /usr/bin/true
    depends_on: [""]

volumes: {"data01", "data02","data", "certs","notebooks"}